# Generated by Django 3.2.9 on 2021-11-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.post'),
            preserve_default=False,
        ),
    ]
