# Generated by Django 3.2.9 on 2021-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211120_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
